import type { ExtractedFact } from '../../models/types';
import type { IRule, RuleViolation } from './rule.interface';

/**
 * R5 — lockfile-package-manager-mismatch
 *
 * Fires when the lockfile present implies a different package manager than
 * what package.json scripts reference.
 *
 * Lockfile facts: source ends with "package-lock.json" | "yarn.lock" |
 *   "pnpm-lock.yaml", key === "package-manager".
 * Script facts: source ends with "package.json", key === "package-manager".
 */
export class DependencyVersionRule implements IRule {
  readonly id = 'lockfile-package-manager-mismatch';
  readonly title = 'Lockfile does not match package.json package manager';

  check(facts: ExtractedFact[]): RuleViolation | null {
    const lockfilePmFacts = facts.filter(
      (f) =>
        f.key === 'package-manager' &&
        /(?:package-lock\.json|yarn\.lock|pnpm-lock\.yaml)$/i.test(f.source),
    );

    const scriptPmFacts = facts.filter(
      (f) =>
        f.key === 'package-manager' &&
        /package\.json$/i.test(f.source),
    );

    if (lockfilePmFacts.length === 0 || scriptPmFacts.length === 0) return null;

    const conflicting: ExtractedFact[] = [];

    for (const lockFact of lockfilePmFacts) {
      for (const scriptFact of scriptPmFacts) {
        if (lockFact.value !== scriptFact.value) {
          if (!conflicting.includes(lockFact)) conflicting.push(lockFact);
          if (!conflicting.includes(scriptFact)) conflicting.push(scriptFact);
        }
      }
    }

    if (conflicting.length === 0) return null;

    return {
      evidence: conflicting.map((f) => ({
        source: f.source,
        key: f.key,
        value: f.value,
        line: f.line,
      })),
      explanation:
        'The lockfile present in the repository was generated by a different ' +
        'package manager than the one referenced in package.json scripts. ' +
        'Running the scripted install command will fail or produce an incorrect ' +
        'dependency tree.',
    };
  }
}
